#!/usr/bin/env bash
# This script configures an Ubuntu server to change localhost to 127.0.0.2 and facebook.com to 8.8.8.8

cp /etc/hosts /etc/hosts.backup

sed -i '/localhost/d' /etc/hosts
sed -i '/facebook.com/d' /etc/hosts


echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
