#!/usr/bin/env bash
# This script configures an Ubuntu server to change localhost to 127.0.0.2 and facebook.com to 8.8.8.8

cp /etc/hosts /etc/hosts.backup

grep -v 'localhost' /etc/hosts | grep -v 'facebook.com' > /tmp/hosts_new

echo "127.0.0.2 localhost" >> /tmp/hosts_new
echo "8.8.8.8 facebook.com" >> /tmp/hosts_new

cp /tmp/hosts_new /etc/hosts

rm /tmp/hosts_new
